language: c
compiler:
        - clang
        - gcc
env:
        - NO_LTO=1
        - CCAN_LD=ld.gold
        -
matrix:
        allowed_failures:
                - compiler: "clang"

script: make
install: ./travis-install.sh
